ignore_stopwords = ['i', 'aboard', 'across', 'accross', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', 'your', 'yours',
         'yourself',
         'yourselves', 'he', 'him', 'his', 'himself', 'she', 'her', 'hers', 'herself', 'it', 'its', 'itself', 'they', 'them',
         'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', 'these', 'those', 'am', 'is', 'are',
         'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the',
         'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against',
         'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on',
         'off', 'over', 'under', 'again', 'further', 'indeed', '', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how',
         'all', 'any', 'both', 'each', 'few', 'more', 'moreover', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only',
         'own', 'same', 'so', 'than', 'too', 'very', 'can', 'will', 'just', 'don', 'should', 'now', 'karkhana', 'said', 'also',
         'last', 'first', 'would', 'could', 'might', 'mr', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine', 'ten',
         'rs', 'new', 'old', 'came', 'went', 'bedmi', 'says', 'say', 'year', 'one', 'per', 'singh', 'made', 'along', 'long',
         'short', 'amid', 'among', 'anti', 'around', 'behind', 'beneath', 'beside', 'besides', 'beyond', 'concerning',
         'considering', 'despite', 'except', 'excepting', 'excluding', 'following', 'inside', 'like', 'minus', 'near', 'onto',
         'opposite', 'outside', 'past', 'plus', 'regarding', 'round', 'save', 'since', 'toward', 'towards', 'underneath', 'unlike',
         'upon', 'versus', 'via', 'within', 'without', 'another', 'together', 'include', 'including', 'exclude', 'led', 'due',
         'various', 'set', 'part', 'parts', 'added', 'many', 'according', 'accordingly', '1', '2', '3', '4', '5', '6', '7', '8',
         '9', '10', 'though', 'although', 'even', 'uneven', 'however', 'left', 'right', 'yet', 'unusual', 'usual', 'using', 'found',
         'high', 'low', 'every', 'take', 'give', 'gave', 'today', 'tomorrow', 'based', 'body', 'monday', 'tuesday', 'wednesday',
         'thursday', 'friday', 'saturday', 'sunday', 'list', 'hours', 'come', 'become', 'became', '20', 'get', 'told', 'behold',
         'days', 'day', 'ltd', 'way', 'away', 'taken', 'given', 'morning', 'afternoon', 'evening', 'night', 'mid night',
         'mid-night', 'midnight', 'additional', 'sought', 'ought', 'next', 'months', 'years', 'january', 'february', 'march',
         'april', 'may', 'june', 'july', 'august', 'september', 'october', 'november', 'december', 'a', 'b', 'c', 'd', 'e', 'f',
         'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', 'special', 'specially',
         'especially', 'file', 'filed', 'make', 'made', 'order', 'ordered', 'yesterday', 'yearly', 'much', 'absolutely', 'always',
         'already', 'annually', 'anxiously', 'anyhow', 'anyplace', 'anyway', 'instance', 'contrary', 'meanwhile', 'anywhere',
         'appreciably', 'appropriately', 'enough', 'entirely', 'equally', 'essentially', 'eternally', 'generally', 'thus', 'warmly',
         'weakly', 'wearily', 'weekly', 'even if', 'unless', 'provided', 'provide', 'till', 'whenever', 'wherever', 'even ',
         'whether', 'finally', 'hence', 'instead', 'nevertheless', 'example', 'likewise', 'still', 'nonetheless', 'therefore',
         'consequently', 'furthermore', 'fact', 'infact', 'namely', 'name', 'otherwise', 'far', 'different', 'see', 'saw', 'seen',
         'being', 'well', 'increase', 'increased', 'decrease', 'decreased', 'must', 'nadu', 'open', 'close', 'complete',
         'completed', 'incomplete', 'ago', 'persons', 'student', 'opened', 'closed', 'back', 'front', 'number', 'numbers', 'km',
         'display', 'displays', 'displayed', 'general', 'cases', 'non', 'use', 'used', 'got', 'com', 'school', 'us', 'several']
